import { beforeEach, expect, it, vi } from "vitest";
import { list } from "./webhookLogs.js";
import WebhookLog from "../../../models/WebhookLog.js";
vi.mock("../../../models/WebhookLog.js", () => ({ default: { aggregate: vi.fn(), aggregatePaginate: vi.fn() } }));
vi.mock("../../../config/index.js", () => ({ envs: { pagination: { limit: 10 } }, StatusError: {} }));
beforeEach(() => vi.clearAllMocks());
it("searches Razorpay references exactly and excludes payloads from list results", async () => {
  WebhookLog.aggregate.mockReturnValue({});
  WebhookLog.aggregatePaginate.mockResolvedValue({ docs: [], totalDocs: 0 });
  const req = { query: { provider: "razorpay", search: "pay_test", page: 2, limit: 25 }, __: value => value };
  const res = { status: vi.fn().mockReturnThis(), json: vi.fn() };
  const next = vi.fn();
  await list(req, res, next);
  expect(next).not.toHaveBeenCalled();
  const pipeline = WebhookLog.aggregate.mock.calls[0][0];
  expect(pipeline[0].$match.provider).toBe("razorpay");
  expect(pipeline[0].$match.$or).toEqual(expect.arrayContaining([{ event_id: "pay_test" }, { provider_order_id: "pay_test" }, { payment_id: "pay_test" }, { refund_id: "pay_test" }]));
  expect(pipeline[2].$project).toMatchObject({ payment_id: 1, signature_verified: 1, processing_state: 1 });
  expect(pipeline[2].$project).not.toHaveProperty("payload");
  expect(WebhookLog.aggregatePaginate).toHaveBeenCalledWith(expect.anything(), { page: 2, limit: 25 });
});
