import { Router } from "express";
import { inventoryRouter } from "./inventory/index.js";
import { masterRouter } from "./master/index.js";
import { customerRouter } from "./customer.js";
import { mediaRouter } from "./media.js";
import { pageRouter } from "./page.js";
import { currencyRouter } from "./currency.js";
import { testimonialRouter } from "./testimonial.js";
import { faqRouter } from "./faq.js";
import { consultationRouter } from "./consultation.js";
import { bannerRouter } from "./banner.js";
import { blogRouter } from "./blog.js";
import { ratingRouter } from "./rating.js";
import { settingsRouter } from "./settings.js";
import { contactUsRouter } from "./contact-us.js";
import { subscriberRouter } from "./subscriber.js";
import { enquiryRouter } from "./enquiry.js";
import { countryRouter } from "./country.js";
import { stateRouter } from "./state.js";
import { cityRouter } from "./city.js";
import { pincodeRouter } from "./pincode.js";
import { shippingRouter } from "./shipping/index.js";
import { seoRouter } from "./seo/index.js";
import { homeRouter } from "./home.js";
import { topbarRouter } from "./topbar.js";
import { headerConfigRouter } from "./header-config.js";
import { navigationMenuRouter } from "./navigation-menu.js";
import { adminNavigationRouter } from "./navigation.js";
import { operationsRouter } from "./operations.js";
import { customersRouter } from "./customers.js";
import { notificationsRouter } from "./notifications.js";
import { emailTemplatesRouter } from "./emailTemplates.js";

const v1AdminRouter = Router();
// All routes go here

v1AdminRouter.use("/inventory", inventoryRouter);
v1AdminRouter.use("/master", masterRouter);
v1AdminRouter.use("/media", mediaRouter);
v1AdminRouter.use("/customer", customerRouter);
v1AdminRouter.use("/page", pageRouter);
v1AdminRouter.use("/currency", currencyRouter);
v1AdminRouter.use("/testimonial", testimonialRouter);
v1AdminRouter.use("/faq", faqRouter);
v1AdminRouter.use("/consultation", consultationRouter);
v1AdminRouter.use("/banner", bannerRouter);
v1AdminRouter.use("/blog", blogRouter);
v1AdminRouter.use("/rating", ratingRouter);
v1AdminRouter.use("/settings", settingsRouter);
v1AdminRouter.use("/contact-us", contactUsRouter);
v1AdminRouter.use("/subscriber", subscriberRouter);
v1AdminRouter.use("/enquiry", enquiryRouter);
v1AdminRouter.use("/country", countryRouter);
v1AdminRouter.use("/state", stateRouter);
v1AdminRouter.use("/city", cityRouter);
v1AdminRouter.use("/pincode", pincodeRouter);
v1AdminRouter.use("/shipping", shippingRouter);
v1AdminRouter.use("/seo", seoRouter);
v1AdminRouter.use("/home", homeRouter);
v1AdminRouter.use("/topbar", topbarRouter);
v1AdminRouter.use("/header-config", headerConfigRouter);
v1AdminRouter.use("/navigation-menu", navigationMenuRouter);
v1AdminRouter.use("/navigation", adminNavigationRouter);
v1AdminRouter.use("/operations", operationsRouter);
v1AdminRouter.use("/customers", customersRouter);
v1AdminRouter.use("/notifications", notificationsRouter);
v1AdminRouter.use("/email-templates", emailTemplatesRouter);

export { v1AdminRouter };
