import { generalHelper } from "../helpers/index.js";
import SiteSetting from "../models/SiteSetting.js";
import Order from "../models/Order.js";
import OrderItem from "../models/OrderItem.js";
import Currency from "../models/Currency.js";
import Country from "../models/Country.js";
import State from "../models/State.js";
import City from "../models/City.js";
import fs from "fs";

import User from "../models/User.js";

export const seed = async function (req, resp) {
  try {
    /**
     * =======================
     * IMPORTING SITE SETTINGS
     * =======================
     */

    // const currency_list = [
    //   {
    //     code: "INR",
    //     name: "Indian Rupee",
    //     symbol: "₹",
    //     country: "India",
    //     flag: "🇮🇳",
    //     icon: "in",
    //     status: "active",
    //   },
    //   {
    //     code: "USD",
    //     name: "United States Dollar",
    //     symbol: "$",
    //     country: "United States",
    //     flag: "🇺🇸",
    //     icon: "us",
    //     status: "active",
    //   },
    //   {
    //     code: "EUR",
    //     name: "Euro",
    //     symbol: "€",
    //     country: "European Union",
    //     flag: "🇪🇺",
    //     icon: "eu",
    //     status: "active",
    //   },
    //   {
    //     code: "GBP",
    //     name: "British Pound Sterling",
    //     symbol: "£",
    //     country: "United Kingdom",
    //     flag: "🇬🇧",
    //     icon: "gb",
    //     status: "active",
    //   },
    //   {
    //     code: "JPY",
    //     name: "Japanese Yen",
    //     symbol: "¥",
    //     country: "Japan",
    //     flag: "🇯🇵",
    //     icon: "jp",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AUD",
    //     name: "Australian Dollar",
    //     symbol: "A$",
    //     country: "Australia",
    //     flag: "🇦🇺",
    //     icon: "au",
    //     status: "active",
    //   },
    //   {
    //     code: "CAD",
    //     name: "Canadian Dollar",
    //     symbol: "C$",
    //     country: "Canada",
    //     flag: "🇨🇦",
    //     icon: "ca",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BDT",
    //     name: "Bangladeshi Taka",
    //     symbol: "৳",
    //     country: "Bangladesh",
    //     flag: "🇧🇩",
    //     icon: "bd",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AED",
    //     name: "United Arab Emirates Dirham",
    //     symbol: "د.إ",
    //     country: "United Arab Emirates",
    //     flag: "🇦🇪",
    //     icon: "ae",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AFN",
    //     name: "Afghan Afghani",
    //     symbol: "؋",
    //     country: "Afghanistan",
    //     flag: "🇦🇫",
    //     icon: "af",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ALL",
    //     name: "Albanian Lek",
    //     symbol: "L",
    //     country: "Albania",
    //     flag: "🇦🇱",
    //     icon: "al",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AMD",
    //     name: "Armenian Dram",
    //     symbol: "֏",
    //     country: "Armenia",
    //     flag: "🇦🇲",
    //     icon: "am",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ANG",
    //     name: "Netherlands Antillean Guilder",
    //     symbol: "ƒ",
    //     country: "Curaçao",
    //     flag: "🇨🇼",
    //     icon: "cw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AOA",
    //     name: "Angolan Kwanza",
    //     symbol: "Kz",
    //     country: "Angola",
    //     flag: "🇦🇴",
    //     icon: "ao",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ARS",
    //     name: "Argentine Peso",
    //     symbol: "$",
    //     country: "Argentina",
    //     flag: "🇦🇷",
    //     icon: "ar",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AWG",
    //     name: "Aruban Florin",
    //     symbol: "ƒ",
    //     country: "Aruba",
    //     flag: "🇦🇼",
    //     icon: "aw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "AZN",
    //     name: "Azerbaijani Manat",
    //     symbol: "₼",
    //     country: "Azerbaijan",
    //     flag: "🇦🇿",
    //     icon: "az",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BAM",
    //     name: "Bosnia-Herzegovina Convertible Mark",
    //     symbol: "KM",
    //     country: "Bosnia and Herzegovina",
    //     flag: "🇧🇦",
    //     icon: "ba",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BBD",
    //     name: "Barbadian Dollar",
    //     symbol: "Bds$",
    //     country: "Barbados",
    //     flag: "🇧🇧",
    //     icon: "bb",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BGN",
    //     name: "Bulgarian Lev",
    //     symbol: "лв",
    //     country: "Bulgaria",
    //     flag: "🇧🇬",
    //     icon: "bg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BHD",
    //     name: "Bahraini Dinar",
    //     symbol: ".د.ب",
    //     country: "Bahrain",
    //     flag: "🇧🇭",
    //     icon: "bh",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BIF",
    //     name: "Burundi Franc",
    //     symbol: "FBu",
    //     country: "Burundi",
    //     flag: "🇧🇮",
    //     icon: "bi",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BMD",
    //     name: "Bermudian Dollar",
    //     symbol: "BD$",
    //     country: "Bermuda",
    //     flag: "🇧🇲",
    //     icon: "bm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BND",
    //     name: "Brunei Dollar",
    //     symbol: "B$",
    //     country: "Brunei",
    //     flag: "🇧🇳",
    //     icon: "bn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BOB",
    //     name: "Bolivian Boliviano",
    //     symbol: "Bs.",
    //     country: "Bolivia",
    //     flag: "🇧🇴",
    //     icon: "bo",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BRL",
    //     name: "Brazilian Real",
    //     symbol: "R$",
    //     country: "Brazil",
    //     flag: "🇧🇷",
    //     icon: "br",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BSD",
    //     name: "Bahamian Dollar",
    //     symbol: "B$",
    //     country: "Bahamas",
    //     flag: "🇧🇸",
    //     icon: "bs",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BTN",
    //     name: "Bhutanese Ngultrum",
    //     symbol: "Nu.",
    //     country: "Bhutan",
    //     flag: "🇧🇹",
    //     icon: "bt",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BWP",
    //     name: "Botswana Pula",
    //     symbol: "P",
    //     country: "Botswana",
    //     flag: "🇧🇼",
    //     icon: "bw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BYN",
    //     name: "Belarusian Ruble",
    //     symbol: "Br",
    //     country: "Belarus",
    //     flag: "🇧🇾",
    //     icon: "by",
    //     status: "inactive",
    //   },
    //   {
    //     code: "BZD",
    //     name: "Belize Dollar",
    //     symbol: "BZ$",
    //     country: "Belize",
    //     flag: "🇧🇿",
    //     icon: "bz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CDF",
    //     name: "Congolese Franc",
    //     symbol: "FC",
    //     country: "Congo (DRC)",
    //     flag: "🇨🇩",
    //     icon: "cd",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CHF",
    //     name: "Swiss Franc",
    //     symbol: "Fr",
    //     country: "Switzerland",
    //     flag: "🇨🇭",
    //     icon: "ch",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CLP",
    //     name: "Chilean Peso",
    //     symbol: "$",
    //     country: "Chile",
    //     flag: "🇨🇱",
    //     icon: "cl",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CNY",
    //     name: "Chinese Yuan",
    //     symbol: "¥",
    //     country: "China",
    //     flag: "🇨🇳",
    //     icon: "cn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "COP",
    //     name: "Colombian Peso",
    //     symbol: "$",
    //     country: "Colombia",
    //     flag: "🇨🇴",
    //     icon: "co",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CRC",
    //     name: "Costa Rican Colón",
    //     symbol: "₡",
    //     country: "Costa Rica",
    //     flag: "🇨🇷",
    //     icon: "cr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CUC",
    //     name: "Cuban Convertible Peso",
    //     symbol: "$",
    //     country: "Cuba",
    //     flag: "🇨🇺",
    //     icon: "cu",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CUP",
    //     name: "Cuban Peso",
    //     symbol: "$",
    //     country: "Cuba",
    //     flag: "🇨🇺",
    //     icon: "cu",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CVE",
    //     name: "Cape Verdean Escudo",
    //     symbol: "Esc",
    //     country: "Cape Verde",
    //     flag: "🇨🇻",
    //     icon: "cv",
    //     status: "inactive",
    //   },
    //   {
    //     code: "CZK",
    //     name: "Czech Koruna",
    //     symbol: "Kč",
    //     country: "Czechia",
    //     flag: "🇨🇿",
    //     icon: "cz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "DJF",
    //     name: "Djiboutian Franc",
    //     symbol: "Fdj",
    //     country: "Djibouti",
    //     flag: "🇩🇯",
    //     icon: "dj",
    //     status: "inactive",
    //   },
    //   {
    //     code: "DKK",
    //     name: "Danish Krone",
    //     symbol: "kr",
    //     country: "Denmark",
    //     flag: "🇩🇰",
    //     icon: "dk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "DOP",
    //     name: "Dominican Peso",
    //     symbol: "RD$",
    //     country: "Dominican Republic",
    //     flag: "🇩🇴",
    //     icon: "do",
    //     status: "inactive",
    //   },
    //   {
    //     code: "DZD",
    //     name: "Algerian Dinar",
    //     symbol: "د.ج",
    //     country: "Algeria",
    //     flag: "🇩🇿",
    //     icon: "dz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "EGP",
    //     name: "Egyptian Pound",
    //     symbol: "£",
    //     country: "Egypt",
    //     flag: "🇪🇬",
    //     icon: "eg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ERN",
    //     name: "Eritrean Nakfa",
    //     symbol: "Nfk",
    //     country: "Eritrea",
    //     flag: "🇪🇷",
    //     icon: "er",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ETB",
    //     name: "Ethiopian Birr",
    //     symbol: "Br",
    //     country: "Ethiopia",
    //     flag: "🇪🇹",
    //     icon: "et",
    //     status: "inactive",
    //   },
    //   {
    //     code: "FJD",
    //     name: "Fijian Dollar",
    //     symbol: "FJ$",
    //     country: "Fiji",
    //     flag: "🇫🇯",
    //     icon: "fj",
    //     status: "inactive",
    //   },
    //   {
    //     code: "FKP",
    //     name: "Falkland Islands Pound",
    //     symbol: "£",
    //     country: "Falkland Islands",
    //     flag: "🇫🇰",
    //     icon: "fk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GEL",
    //     name: "Georgian Lari",
    //     symbol: "₾",
    //     country: "Georgia",
    //     flag: "🇬🇪",
    //     icon: "ge",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GHS",
    //     name: "Ghanaian Cedi",
    //     symbol: "₵",
    //     country: "Ghana",
    //     flag: "🇬🇭",
    //     icon: "gh",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GIP",
    //     name: "Gibraltar Pound",
    //     symbol: "£",
    //     country: "Gibraltar",
    //     flag: "🇬🇮",
    //     icon: "gi",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GMD",
    //     name: "Gambian Dalasi",
    //     symbol: "D",
    //     country: "Gambia",
    //     flag: "🇬🇲",
    //     icon: "gm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GNF",
    //     name: "Guinean Franc",
    //     symbol: "FG",
    //     country: "Guinea",
    //     flag: "🇬🇳",
    //     icon: "gn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GTQ",
    //     name: "Guatemalan Quetzal",
    //     symbol: "Q",
    //     country: "Guatemala",
    //     flag: "🇬🇹",
    //     icon: "gt",
    //     status: "inactive",
    //   },
    //   {
    //     code: "GYD",
    //     name: "Guyanese Dollar",
    //     symbol: "GY$",
    //     country: "Guyana",
    //     flag: "🇬🇾",
    //     icon: "gy",
    //     status: "inactive",
    //   },
    //   {
    //     code: "HKD",
    //     name: "Hong Kong Dollar",
    //     symbol: "HK$",
    //     country: "Hong Kong",
    //     flag: "🇭🇰",
    //     icon: "hk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "HNL",
    //     name: "Honduran Lempira",
    //     symbol: "L",
    //     country: "Honduras",
    //     flag: "🇭🇳",
    //     icon: "hn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "HRK",
    //     name: "Croatian Kuna",
    //     symbol: "kn",
    //     country: "Croatia",
    //     flag: "🇭🇷",
    //     icon: "hr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "HTG",
    //     name: "Haitian Gourde",
    //     symbol: "G",
    //     country: "Haiti",
    //     flag: "🇭🇹",
    //     icon: "ht",
    //     status: "inactive",
    //   },
    //   {
    //     code: "HUF",
    //     name: "Hungarian Forint",
    //     symbol: "Ft",
    //     country: "Hungary",
    //     flag: "🇭🇺",
    //     icon: "hu",
    //     status: "inactive",
    //   },
    //   {
    //     code: "IDR",
    //     name: "Indonesian Rupiah",
    //     symbol: "Rp",
    //     country: "Indonesia",
    //     flag: "🇮🇩",
    //     icon: "id",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ILS",
    //     name: "Israeli New Shekel",
    //     symbol: "₪",
    //     country: "Israel",
    //     flag: "🇮🇱",
    //     icon: "il",
    //     status: "inactive",
    //   },
    //   {
    //     code: "IQD",
    //     name: "Iraqi Dinar",
    //     symbol: "ع.د",
    //     country: "Iraq",
    //     flag: "🇮🇶",
    //     icon: "iq",
    //     status: "inactive",
    //   },
    //   {
    //     code: "IRR",
    //     name: "Iranian Rial",
    //     symbol: "﷼",
    //     country: "Iran",
    //     flag: "🇮🇷",
    //     icon: "ir",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ISK",
    //     name: "Icelandic Króna",
    //     symbol: "kr",
    //     country: "Iceland",
    //     flag: "🇮🇸",
    //     icon: "is",
    //     status: "inactive",
    //   },
    //   {
    //     code: "JMD",
    //     name: "Jamaican Dollar",
    //     symbol: "J$",
    //     country: "Jamaica",
    //     flag: "🇯🇲",
    //     icon: "jm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "JOD",
    //     name: "Jordanian Dinar",
    //     symbol: "JD",
    //     country: "Jordan",
    //     flag: "🇯🇴",
    //     icon: "jo",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KES",
    //     name: "Kenyan Shilling",
    //     symbol: "KSh",
    //     country: "Kenya",
    //     flag: "🇰🇪",
    //     icon: "ke",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KGS",
    //     name: "Kyrgyzstani Som",
    //     symbol: "лв",
    //     country: "Kyrgyzstan",
    //     flag: "🇰🇬",
    //     icon: "kg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KHR",
    //     name: "Cambodian Riel",
    //     symbol: "៛",
    //     country: "Cambodia",
    //     flag: "🇰🇭",
    //     icon: "kh",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KMF",
    //     name: "Comorian Franc",
    //     symbol: "CF",
    //     country: "Comoros",
    //     flag: "🇰🇲",
    //     icon: "km",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KPW",
    //     name: "North Korean Won",
    //     symbol: "₩",
    //     country: "North Korea",
    //     flag: "🇰🇵",
    //     icon: "kp",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KRW",
    //     name: "South Korean Won",
    //     symbol: "₩",
    //     country: "South Korea",
    //     flag: "🇰🇷",
    //     icon: "kr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KWD",
    //     name: "Kuwaiti Dinar",
    //     symbol: "د.ك",
    //     country: "Kuwait",
    //     flag: "🇰🇼",
    //     icon: "kw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KYD",
    //     name: "Cayman Islands Dollar",
    //     symbol: "CI$",
    //     country: "Cayman Islands",
    //     flag: "🇰🇾",
    //     icon: "ky",
    //     status: "inactive",
    //   },
    //   {
    //     code: "KZT",
    //     name: "Kazakhstani Tenge",
    //     symbol: "₸",
    //     country: "Kazakhstan",
    //     flag: "🇰🇿",
    //     icon: "kz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LAK",
    //     name: "Lao Kip",
    //     symbol: "₭",
    //     country: "Laos",
    //     flag: "🇱🇦",
    //     icon: "la",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LBP",
    //     name: "Lebanese Pound",
    //     symbol: "£",
    //     country: "Lebanon",
    //     flag: "🇱🇧",
    //     icon: "lb",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LKR",
    //     name: "Sri Lankan Rupee",
    //     symbol: "Rs",
    //     country: "Sri Lanka",
    //     flag: "🇱🇰",
    //     icon: "lk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LRD",
    //     name: "Liberian Dollar",
    //     symbol: "L$",
    //     country: "Liberia",
    //     flag: "🇱🇷",
    //     icon: "lr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LSL",
    //     name: "Lesotho Loti",
    //     symbol: "M",
    //     country: "Lesotho",
    //     flag: "🇱🇸",
    //     icon: "ls",
    //     status: "inactive",
    //   },
    //   {
    //     code: "LYD",
    //     name: "Libyan Dinar",
    //     symbol: "ل.د",
    //     country: "Libya",
    //     flag: "🇱🇾",
    //     icon: "ly",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MAD",
    //     name: "Moroccan Dirham",
    //     symbol: "د.م.",
    //     country: "Morocco",
    //     flag: "🇲🇦",
    //     icon: "ma",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MDL",
    //     name: "Moldovan Leu",
    //     symbol: "L",
    //     country: "Moldova",
    //     flag: "🇲🇩",
    //     icon: "md",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MGA",
    //     name: "Malagasy Ariary",
    //     symbol: "Ar",
    //     country: "Madagascar",
    //     flag: "🇲🇬",
    //     icon: "mg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MKD",
    //     name: "Macedonian Denar",
    //     symbol: "ден",
    //     country: "North Macedonia",
    //     flag: "🇲🇰",
    //     icon: "mk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MMK",
    //     name: "Myanmar Kyat",
    //     symbol: "K",
    //     country: "Myanmar",
    //     flag: "🇲🇲",
    //     icon: "mm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MNT",
    //     name: "Mongolian Tögrög",
    //     symbol: "₮",
    //     country: "Mongolia",
    //     flag: "🇲🇳",
    //     icon: "mn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MOP",
    //     name: "Macanese Pataca",
    //     symbol: "P",
    //     country: "Macau",
    //     flag: "🇲🇴",
    //     icon: "mo",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MRU",
    //     name: "Mauritanian Ouguiya",
    //     symbol: "UM",
    //     country: "Mauritania",
    //     flag: "🇲🇷",
    //     icon: "mr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MUR",
    //     name: "Mauritian Rupee",
    //     symbol: "₨",
    //     country: "Mauritius",
    //     flag: "🇲🇺",
    //     icon: "mu",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MVR",
    //     name: "Maldivian Rufiyaa",
    //     symbol: "Rf",
    //     country: "Maldives",
    //     flag: "🇲🇻",
    //     icon: "mv",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MWK",
    //     name: "Malawian Kwacha",
    //     symbol: "MK",
    //     country: "Malawi",
    //     flag: "🇲🇼",
    //     icon: "mw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MXN",
    //     name: "Mexican Peso",
    //     symbol: "$",
    //     country: "Mexico",
    //     flag: "🇲🇽",
    //     icon: "mx",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MYR",
    //     name: "Malaysian Ringgit",
    //     symbol: "RM",
    //     country: "Malaysia",
    //     flag: "🇲🇾",
    //     icon: "my",
    //     status: "inactive",
    //   },
    //   {
    //     code: "MZN",
    //     name: "Mozambican Metical",
    //     symbol: "MT",
    //     country: "Mozambique",
    //     flag: "🇲🇿",
    //     icon: "mz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NAD",
    //     name: "Namibian Dollar",
    //     symbol: "N$",
    //     country: "Namibia",
    //     flag: "🇳🇦",
    //     icon: "na",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NGN",
    //     name: "Nigerian Naira",
    //     symbol: "₦",
    //     country: "Nigeria",
    //     flag: "🇳🇬",
    //     icon: "ng",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NIO",
    //     name: "Nicaraguan Córdoba",
    //     symbol: "C$",
    //     country: "Nicaragua",
    //     flag: "🇳🇮",
    //     icon: "ni",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NOK",
    //     name: "Norwegian Krone",
    //     symbol: "kr",
    //     country: "Norway",
    //     flag: "🇳🇴",
    //     icon: "no",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NPR",
    //     name: "Nepalese Rupee",
    //     symbol: "₨",
    //     country: "Nepal",
    //     flag: "🇳🇵",
    //     icon: "np",
    //     status: "inactive",
    //   },
    //   {
    //     code: "NZD",
    //     name: "New Zealand Dollar",
    //     symbol: "NZ$",
    //     country: "New Zealand",
    //     flag: "🇳🇿",
    //     icon: "nz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "OMR",
    //     name: "Omani Rial",
    //     symbol: "ر.ع.",
    //     country: "Oman",
    //     flag: "🇴🇲",
    //     icon: "om",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PAB",
    //     name: "Panamanian Balboa",
    //     symbol: "B./",
    //     country: "Panama",
    //     flag: "🇵🇦",
    //     icon: "pa",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PEN",
    //     name: "Peruvian Sol",
    //     symbol: "S/.",
    //     country: "Peru",
    //     flag: "🇵🇪",
    //     icon: "pe",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PGK",
    //     name: "Papua New Guinean Kina",
    //     symbol: "K",
    //     country: "Papua New Guinea",
    //     flag: "🇵🇬",
    //     icon: "pg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PHP",
    //     name: "Philippine Peso",
    //     symbol: "₱",
    //     country: "Philippines",
    //     flag: "🇵🇭",
    //     icon: "ph",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PKR",
    //     name: "Pakistani Rupee",
    //     symbol: "₨",
    //     country: "Pakistan",
    //     flag: "🇵🇰",
    //     icon: "pk",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PLN",
    //     name: "Polish Złoty",
    //     symbol: "zł",
    //     country: "Poland",
    //     flag: "🇵🇱",
    //     icon: "pl",
    //     status: "inactive",
    //   },
    //   {
    //     code: "PYG",
    //     name: "Paraguayan Guaraní",
    //     symbol: "₲",
    //     country: "Paraguay",
    //     flag: "🇵🇾",
    //     icon: "py",
    //     status: "inactive",
    //   },
    //   {
    //     code: "QAR",
    //     name: "Qatari Riyal",
    //     symbol: "ر.ق",
    //     country: "Qatar",
    //     flag: "🇶🇦",
    //     icon: "qa",
    //     status: "inactive",
    //   },
    //   {
    //     code: "RON",
    //     name: "Romanian Leu",
    //     symbol: "L",
    //     country: "Romania",
    //     flag: "🇷🇴",
    //     icon: "ro",
    //     status: "inactive",
    //   },
    //   {
    //     code: "RSD",
    //     name: "Serbian Dinar",
    //     symbol: "дин.",
    //     country: "Serbia",
    //     flag: "🇷🇸",
    //     icon: "rs",
    //     status: "inactive",
    //   },
    //   {
    //     code: "RUB",
    //     name: "Russian Ruble",
    //     symbol: "₽",
    //     country: "Russia",
    //     flag: "🇷🇺",
    //     icon: "ru",
    //     status: "inactive",
    //   },
    //   {
    //     code: "RWF",
    //     name: "Rwandan Franc",
    //     symbol: "FRw",
    //     country: "Rwanda",
    //     flag: "🇷🇼",
    //     icon: "rw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SAR",
    //     name: "Saudi Riyal",
    //     symbol: "ر.س",
    //     country: "Saudi Arabia",
    //     flag: "🇸🇦",
    //     icon: "sa",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SBD",
    //     name: "Solomon Islands Dollar",
    //     symbol: "SI$",
    //     country: "Solomon Islands",
    //     flag: "🇸🇧",
    //     icon: "sb",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SCR",
    //     name: "Seychellois Rupee",
    //     symbol: "₨",
    //     country: "Seychelles",
    //     flag: "🇸🇨",
    //     icon: "sc",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SDG",
    //     name: "Sudanese Pound",
    //     symbol: "£",
    //     country: "Sudan",
    //     flag: "🇸🇩",
    //     icon: "sd",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SEK",
    //     name: "Swedish Krona",
    //     symbol: "kr",
    //     country: "Sweden",
    //     flag: "🇸🇪",
    //     icon: "se",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SGD",
    //     name: "Singapore Dollar",
    //     symbol: "S$",
    //     country: "Singapore",
    //     flag: "🇸🇬",
    //     icon: "sg",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SHP",
    //     name: "Saint Helena Pound",
    //     symbol: "£",
    //     country: "Saint Helena",
    //     flag: "🇸🇭",
    //     icon: "sh",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SLL",
    //     name: "Sierra Leonean Leone",
    //     symbol: "Le",
    //     country: "Sierra Leone",
    //     flag: "🇸🇱",
    //     icon: "sl",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SOS",
    //     name: "Somali Shilling",
    //     symbol: "S",
    //     country: "Somalia",
    //     flag: "🇸🇴",
    //     icon: "so",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SRD",
    //     name: "Surinamese Dollar",
    //     symbol: "$",
    //     country: "Suriname",
    //     flag: "🇸🇷",
    //     icon: "sr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SSP",
    //     name: "South Sudanese Pound",
    //     symbol: "£",
    //     country: "South Sudan",
    //     flag: "🇸🇸",
    //     icon: "ss",
    //     status: "inactive",
    //   },
    //   {
    //     code: "STN",
    //     name: "São Tomé and Príncipe Dobra",
    //     symbol: "Db",
    //     country: "São Tomé and Príncipe",
    //     flag: "🇸🇹",
    //     icon: "st",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SVC",
    //     name: "Salvadoran Colón",
    //     symbol: "₡",
    //     country: "El Salvador",
    //     flag: "🇸🇻",
    //     icon: "sv",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SYP",
    //     name: "Syrian Pound",
    //     symbol: "£",
    //     country: "Syria",
    //     flag: "🇸🇾",
    //     icon: "sy",
    //     status: "inactive",
    //   },
    //   {
    //     code: "SZL",
    //     name: "Swazi Lilangeni",
    //     symbol: "E",
    //     country: "Eswatini",
    //     flag: "🇸🇿",
    //     icon: "sz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "THB",
    //     name: "Thai Baht",
    //     symbol: "฿",
    //     country: "Thailand",
    //     flag: "🇹🇭",
    //     icon: "th",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TJS",
    //     name: "Tajikistani Somoni",
    //     symbol: "ЅМ",
    //     country: "Tajikistan",
    //     flag: "🇹🇯",
    //     icon: "tj",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TMT",
    //     name: "Turkmenistan Manat",
    //     symbol: "m",
    //     country: "Turkmenistan",
    //     flag: "🇹🇲",
    //     icon: "tm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TND",
    //     name: "Tunisian Dinar",
    //     symbol: "د.ت",
    //     country: "Tunisia",
    //     flag: "🇹🇳",
    //     icon: "tn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TOP",
    //     name: "Tongan Paʻanga",
    //     symbol: "T$",
    //     country: "Tonga",
    //     flag: "🇹🇴",
    //     icon: "to",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TRY",
    //     name: "Turkish Lira",
    //     symbol: "₺",
    //     country: "Turkey",
    //     flag: "🇹🇷",
    //     icon: "tr",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TTD",
    //     name: "Trinidad and Tobago Dollar",
    //     symbol: "TT$",
    //     country: "Trinidad and Tobago",
    //     flag: "🇹🇹",
    //     icon: "tt",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TWD",
    //     name: "New Taiwan Dollar",
    //     symbol: "NT$",
    //     country: "Taiwan",
    //     flag: "🇹🇼",
    //     icon: "tw",
    //     status: "inactive",
    //   },
    //   {
    //     code: "TZS",
    //     name: "Tanzanian Shilling",
    //     symbol: "TSh",
    //     country: "Tanzania",
    //     flag: "🇹🇿",
    //     icon: "tz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "UAH",
    //     name: "Ukrainian Hryvnia",
    //     symbol: "₴",
    //     country: "Ukraine",
    //     flag: "🇺🇦",
    //     icon: "ua",
    //     status: "inactive",
    //   },
    //   {
    //     code: "UGX",
    //     name: "Ugandan Shilling",
    //     symbol: "USh",
    //     country: "Uganda",
    //     flag: "🇺🇬",
    //     icon: "ug",
    //     status: "inactive",
    //   },
    //   {
    //     code: "UYU",
    //     name: "Uruguayan Peso",
    //     symbol: "$U",
    //     country: "Uruguay",
    //     flag: "🇺🇾",
    //     icon: "uy",
    //     status: "inactive",
    //   },
    //   {
    //     code: "UZS",
    //     name: "Uzbekistan Som",
    //     symbol: "сўм",
    //     country: "Uzbekistan",
    //     flag: "🇺🇿",
    //     icon: "uz",
    //     status: "inactive",
    //   },
    //   {
    //     code: "VES",
    //     name: "Venezuelan Bolívar Soberano",
    //     symbol: "Bs.S",
    //     country: "Venezuela",
    //     flag: "🇻🇪",
    //     icon: "ve",
    //     status: "inactive",
    //   },
    //   {
    //     code: "VND",
    //     name: "Vietnamese Đồng",
    //     symbol: "₫",
    //     country: "Vietnam",
    //     flag: "🇻🇳",
    //     icon: "vn",
    //     status: "inactive",
    //   },
    //   {
    //     code: "VUV",
    //     name: "Vanuatu Vatu",
    //     symbol: "VT",
    //     country: "Vanuatu",
    //     flag: "🇻🇺",
    //     icon: "vu",
    //     status: "inactive",
    //   },
    //   {
    //     code: "WST",
    //     name: "Samoan Tala",
    //     symbol: "T",
    //     country: "Samoa",
    //     flag: "🇼🇸",
    //     icon: "ws",
    //     status: "inactive",
    //   },
    //   {
    //     code: "XAF",
    //     name: "CFA Franc BEAC",
    //     symbol: "FCFA",
    //     country: "Central African States",
    //     flag: "🇨🇫",
    //     icon: "cf",
    //     status: "inactive",
    //   },
    //   {
    //     code: "XCD",
    //     name: "East Caribbean Dollar",
    //     symbol: "EC$",
    //     country: "East Caribbean States",
    //     flag: "🇦🇮",
    //     icon: "ai",
    //     status: "inactive",
    //   },
    //   {
    //     code: "XOF",
    //     name: "CFA Franc BCEAO",
    //     symbol: "CFA",
    //     country: "West African States",
    //     flag: "🇧🇯",
    //     icon: "bj",
    //     status: "inactive",
    //   },
    //   {
    //     code: "XPF",
    //     name: "CFP Franc",
    //     symbol: "₣",
    //     country: "French Pacific Territories",
    //     flag: "🇵🇫",
    //     icon: "pf",
    //     status: "inactive",
    //   },
    //   {
    //     code: "YER",
    //     name: "Yemeni Rial",
    //     symbol: "﷼",
    //     country: "Yemen",
    //     flag: "🇾🇪",
    //     icon: "ye",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ZAR",
    //     name: "South African Rand",
    //     symbol: "R",
    //     country: "South Africa",
    //     flag: "🇿🇦",
    //     icon: "za",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ZMW",
    //     name: "Zambian Kwacha",
    //     symbol: "ZK",
    //     country: "Zambia",
    //     flag: "🇿🇲",
    //     icon: "zm",
    //     status: "inactive",
    //   },
    //   {
    //     code: "ZWL",
    //     name: "Zimbabwean Dollar",
    //     symbol: "$",
    //     country: "Zimbabwe",
    //     flag: "🇿🇼",
    //     icon: "zw",
    //     status: "inactive",
    //   },
    // ];

    // for (const currency of currency_list) {
    //   const updateDoc = {
    //     ...currency,
    //   };

    //   await Currency.updateOne({ code: currency.code }, updateDoc, {
    //     upsert: true,
    //   });
    // }
    const settings = [
      {
        slug: "site_title",
        value: "Elexify Industries",
        label: "Site Title",
        type: "site_info",
      },
      {
        slug: "site_tagline",
        value: "Transform your life with Energized Rudraksha",
        label: "Site Tagline",
        type: "site_info",
      },
      {
        slug: "contact_mobile",
        value: "9064401121",
        label: "Contact Mobile",
        type: "contact_info",
      },
      {
        slug: "contact_mobile_2",
        value: "8906787168",
        label: "Contact Mobile 2",
        type: "contact_info",
      },
      {
        slug: "contact_email",
        value: "support@baseweb.in",
        label: "Contact Email",
        type: "contact_info",
      },
      {
        slug: "contact_address",
        value: "Saltlake, Kolkata - 700091",
        label: "Contact Address",
        type: "contact_info",
      },
      {
        slug: "low_stock_threshold",
        value: "5",
        label: "Low Stock Threshold",
        type: "product_info",
      },
      {
        slug: "rudraksha_consultation_fee",
        value: "1500",
        label: "Rudraksha Consultation Fee",
        type: "consultation_fee",
      },
      {
        slug: "astro_consultation_fee",
        value: "1500",
        label: "Astro Consultation Fee",
        type: "consultation_fee",
      },
    ];

    for (const setting of settings) {
      const updateDoc = {
        slug: setting.slug,
        label: setting.label,
        type: setting.type,
        value: setting.value,
      };

      await SiteSetting.updateOne({ slug: setting.slug }, updateDoc, {
        upsert: true,
      });
    }

    /**
     * ==================================
     * INSERTING SUPERADMIN IF NOT EXISTS
     * ==================================
     */
    const adminCount = await User.countDocuments({
      role: "superadmin",
      deleted_at: null,
    });

    if (adminCount < 1) {
      const document = {
        role: "superadmin",
        name: "Super Admin",
        email: "superadmin@rudrakshavalley.com",
        password: await generalHelper.bcryptMake("Rudraksha@2025"),
      };

      await User.create(document);
    }
    // const countries = JSON.parse(
    //   fs.readFileSync("./src/assets/locales/countries.json", "utf-8")
    // );
    // await Country.insertMany(countries);

    // // States and Cities seeding can be done similarly if needed
    // const states = JSON.parse(
    //   fs.readFileSync("./src/assets/locales/states.json", "utf-8")
    // );
    // await State.insertMany(states);

    // const cities = JSON.parse(
    //   fs.readFileSync("./src/assets/locales/cities.json", "utf-8")
    // );
    // await City.insertMany(cities);

    const TotalOrders = await Order.find({});
    for (const order of TotalOrders) {
      if (order._id) {
        const orderItems = await OrderItem.find({ order_id: order._id });
        await Order.updateOne(
          { _id: order._id },
          { total_items: orderItems.length }
        );
      }
    }

    return resp.send(`
      <h3 style="text-align: center; padding: 10% 0; text-transform: uppercase;">
        ✅ DB Seeding Completed
      </h3>
    `);
  } catch (err) {
    console.error("Seeding Process Error:", err);
    return resp.status(500).send("❌ Seeding Failed. Check server logs.");
  }
};
